#!/usr/bin/env python3
# Mirrored in CI by testkit's FixturesSuite; keep the two in step.
"""Calibrate the tolerance classes against the Cox and logistic reference fixtures (D-09, NN-9; ADR-0005).

For each case and tie method it reports, under the comparison rule of testkit's `Tolerance`
(element i passes when |a_i - e_i| <= atol + rtol * max(|e_i|, s), s = max_j |e_j|), the worst
ratio of observed difference to allowed difference:
  - pprof_py against R survival::coxph (two validated implementations): must be at most 1;
  - each negative control against pprof_py: must be at least MARGIN, so a real defect fails.
Writes docs/parity/cox-calibration.md and logistic-calibration.md. Usage: python reference/fixtures/calibrate.py
"""

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MARGIN = 10.0

QUANTITIES = (("coef", "T-coef"), ("se", "T-var"), ("covariance", "T-var"), ("loglik", "T-fn"))
FUNCTION = (("loglik", "T-fn"), ("score", "T-fn"), ("information", "T-fn"))


def tolerances():
    values = {}
    with open(os.path.join(ROOT, "testkit", "src", "main", "resources", "tolerances.conf"), encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line and not line.startswith("#"):
                key, value = (part.strip() for part in line.split("=", 1))
                values[key] = float(value)
    return values


def ratio(tol, cls, actual, expected):
    rtol, atol = tol[f"{cls}.rtol"], tol[f"{cls}.atol"]
    a = np.array([float.fromhex(v) for v in actual])
    e = np.array([float.fromhex(v) for v in expected])
    scale = float(np.max(np.abs(e)))
    allowed = atol + rtol * np.maximum(np.abs(e), scale)
    diff = np.abs(a - e)
    with np.errstate(divide="ignore", invalid="ignore"):
        r = np.where(diff == 0.0, 0.0, diff / allowed)
    return float(np.max(r))


LOGISTIC_GLM = (("beta", "T-coef"), ("gamma", "T-coef"), ("var_beta", "T-var"), ("var_gamma", "T-var"),
                ("var_case_mix", "T-var"), ("loglik", "T-fn"))
LOGISTIC_SERBIN = (("default", "beta"), ("default", "gamma"), ("tight", "beta"), ("tight", "gamma"))


def logistic(tol, manifest, fixtures):
    """pprof_py against stats::glm (tight fits) and R pprof's SerBIN (default and tight), and the negative
    controls against pprof_py's tight fit; writes docs/parity/logistic-calibration.md."""
    rows, failures, informational = [], [], []
    for case in manifest["cases"].get("logistic", []):
        py = json.load(open(os.path.join(fixtures, "logistic", case, "pprof_py.json"), encoding="utf-8"))
        r = json.load(open(os.path.join(fixtures, "logistic", case, "r_logistic.json"), encoding="utf-8"))
        checks = [(f"{q} vs glm (tight fits)", cls, py["tight"][q], r["glm"][q]) for q, cls in LOGISTIC_GLM if "glm" in r]
        checks += [(f"{q} vs R SerBIN ({fit})", "T-coef", py[fit][q], r[f"serbin_{fit}"][q]) for fit, q in LOGISTIC_SERBIN]
        for label, cls, a, e in checks:
            agreement = ratio(tol, cls, a, e)
            ok = agreement <= 1.0
            if not ok:
                failures.append((case, label))
            rows.append((case, label, cls, f"{agreement:.3g}", "yes" if ok else "**no**"))
        for q, cls in LOGISTIC_GLM:
            for name, control in py["negative_controls"].items():
                miss = ratio(tol, cls, control[q], py["tight"][q])
                ok = miss >= MARGIN
                if not ok:
                    failures.append((case, f"{name} {q}"))
                rows.append((case, f"negative control {name}: {q}", cls, f"{miss:.3g}", "yes" if ok else "**no**"))
        if "glm_nondegenerate" in r:
            informational.append(f"- {case}: pprof_py's tight β̂ against `glm` without the degenerate providers is "
                                 f"{ratio(tol, 'T-coef', py['tight']['beta'], r['glm_nondegenerate']['beta']):.3g} of T-coef "
                                 "(X-018: the bound keeps their records in the β score; not a parity check)")
    lines = ["# Logistic fixed-effect tolerance calibration (D-09, D-30)", "",
             "Generated by `reference/fixtures/calibrate.py` from the fixtures of pprof_py "
             f"{manifest['reference']['pprof_py']['version']}, R {manifest['reference']['r']['version']} (`stats::glm`) "
             f"and R pprof {manifest['reference']['r_pprof']['version']} (`logis_BIN_fe_prov`). Ratios are observed "
             "difference over allowed difference under testkit's `Tolerance` rule: agreement must be at most 1 and "
             f"every negative control, compared with pprof_py's tight fit, at least {MARGIN:g}.", "",
             "| Case | Comparison | Class | Ratio | OK |", "|---|---|---|---|---|"]
    lines += [f"| {case} | {label} | {cls} | {value} | {ok} |" for case, label, cls, value, ok in rows]
    lines += [""] + informational + ["", f"Result: {'all checks pass' if not failures else f'{len(failures)} checks fail'}."]
    with open(os.path.join(ROOT, "docs", "parity", "logistic-calibration.md"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print("logistic:", lines[-1])
    for failure in failures:
        print("FAIL", *failure)
    return failures


def main():
    tol = tolerances()
    fixtures = os.path.join(ROOT, "fixtures")
    manifest = json.load(open(os.path.join(fixtures, "manifest.json"), encoding="utf-8"))
    rows, failures = [], []
    for case in manifest["cases"]["cox"]:
        py = json.load(open(os.path.join(fixtures, "cox", case, "pprof_py.json"), encoding="utf-8"))
        r = json.load(open(os.path.join(fixtures, "cox", case, "r_survival.json"), encoding="utf-8"))
        for ties in ("breslow", "efron"):
            checks = [(f"{q} (tight fit)", cls, py[ties]["tight"][q], r[ties]["tight"][q]) for q, cls in QUANTITIES]
            checks += [(f"{q} at {b}", cls, py[ties][b][q], r[ties][b][q]) for b in ("beta_zero", "beta_fixed") for q, cls in FUNCTION]
            for label, cls, a, e in checks:
                agreement = ratio(tol, cls, a, e)
                controls = {name: ratio(tol, cls, fit[label.split(" ")[0]], py[ties]["tight"][label.split(" ")[0]])
                            for name, fit in py[ties]["negative_controls"].items()} if "tight" in label else {}
                weakest = min(controls.values()) if controls else None
                ok = agreement <= 1.0 and (weakest is None or weakest >= MARGIN)
                if not ok:
                    failures.append((case, ties, label))
                rows.append((case, ties, label, cls, agreement, weakest, ok))
            rows.append((case, ties, "iterations, default control", "exact",
                         abs(py[ties]["default"]["iterations"] - r[ties]["default"]["iterations"]), None,
                         py[ties]["default"]["iterations"] == r[ties]["default"]["iterations"]))

    lines = ["# Cox tolerance calibration (D-09)", "",
             "Generated by `reference/fixtures/calibrate.py` from the fixtures of pprof_py "
             f"{manifest['reference']['pprof_py']['version']} and R {manifest['reference']['r']['version']} "
             f"with survival {manifest['reference']['r']['survival']}. Ratios are observed difference over allowed "
             "difference under testkit's `Tolerance` rule. Agreement between the two validated implementations "
             f"must be at most 1; every negative control must be at least {MARGIN:g}.", "",
             "| Case | Ties | Quantity | Class | pprof_py vs R | Weakest negative control | OK |",
             "|---|---|---|---|---|---|---|"]
    for case, ties, label, cls, agreement, weakest, ok in rows:
        agreement_text = f"{agreement:d}" if isinstance(agreement, int) else f"{agreement:.3g}"
        weakest_text = "—" if weakest is None else f"{weakest:.3g}"
        lines.append(f"| {case} | {ties} | {label} | {cls} | {agreement_text} | {weakest_text} | {'yes' if ok else '**no**'} |")
    lines += ["", f"Result: {'all checks pass' if not failures else f'{len(failures)} checks fail'}."]
    os.makedirs(os.path.join(ROOT, "docs", "parity"), exist_ok=True)
    with open(os.path.join(ROOT, "docs", "parity", "cox-calibration.md"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print("\n".join(lines[-1:]))
    for failure in failures:
        print("FAIL", *failure)
    failures += logistic(tol, manifest, fixtures)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
