#!/usr/bin/env python3
# Mirrored in CI by testkit's FixturesSuite; keep the two in step.
"""Calibrate the Cox tolerance classes against the reference fixtures (D-09, NN-9; ADR-0005).

For each case and tie method it reports, under the comparison rule of testkit's `Tolerance`
(element i passes when |a_i - e_i| <= atol + rtol * max(|e_i|, s), s = max_j |e_j|), the worst
ratio of observed difference to allowed difference:
  - pprof_py against R survival::coxph (two validated implementations): must be at most 1;
  - each negative control against pprof_py: must be at least MARGIN, so a real defect fails.
Writes docs/parity/cox-calibration.md. Usage: python reference/fixtures/calibrate.py
"""

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MARGIN = 10.0

QUANTITIES = (("coef", "T-coef"), ("se", "T-var"), ("covariance", "T-var"), ("loglik", "T-fn"))
FUNCTION = (("loglik", "T-fn"), ("score", "T-fn"), ("information", "T-fn"))


def tolerances():
    values = {}
    with open(os.path.join(ROOT, "testkit", "src", "main", "resources", "tolerances.conf"), encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line and not line.startswith("#"):
                key, value = (part.strip() for part in line.split("=", 1))
                values[key] = float(value)
    return values


def ratio(tol, cls, actual, expected):
    rtol, atol = tol[f"{cls}.rtol"], tol[f"{cls}.atol"]
    a = np.array([float.fromhex(v) for v in actual])
    e = np.array([float.fromhex(v) for v in expected])
    scale = float(np.max(np.abs(e)))
    allowed = atol + rtol * np.maximum(np.abs(e), scale)
    diff = np.abs(a - e)
    with np.errstate(divide="ignore", invalid="ignore"):
        r = np.where(diff == 0.0, 0.0, diff / allowed)
    return float(np.max(r))


def main():
    tol = tolerances()
    fixtures = os.path.join(ROOT, "fixtures")
    manifest = json.load(open(os.path.join(fixtures, "manifest.json"), encoding="utf-8"))
    rows, failures = [], []
    for case in manifest["cases"]["cox"]:
        py = json.load(open(os.path.join(fixtures, "cox", case, "pprof_py.json"), encoding="utf-8"))
        r = json.load(open(os.path.join(fixtures, "cox", case, "r_survival.json"), encoding="utf-8"))
        for ties in ("breslow", "efron"):
            checks = [(f"{q} (tight fit)", cls, py[ties]["tight"][q], r[ties]["tight"][q]) for q, cls in QUANTITIES]
            checks += [(f"{q} at {b}", cls, py[ties][b][q], r[ties][b][q]) for b in ("beta_zero", "beta_fixed") for q, cls in FUNCTION]
            for label, cls, a, e in checks:
                agreement = ratio(tol, cls, a, e)
                controls = {name: ratio(tol, cls, fit[label.split(" ")[0]], py[ties]["tight"][label.split(" ")[0]])
                            for name, fit in py[ties]["negative_controls"].items()} if "tight" in label else {}
                weakest = min(controls.values()) if controls else None
                ok = agreement <= 1.0 and (weakest is None or weakest >= MARGIN)
                if not ok:
                    failures.append((case, ties, label))
                rows.append((case, ties, label, cls, agreement, weakest, ok))
            rows.append((case, ties, "iterations, default control", "exact",
                         abs(py[ties]["default"]["iterations"] - r[ties]["default"]["iterations"]), None,
                         py[ties]["default"]["iterations"] == r[ties]["default"]["iterations"]))

    lines = ["# Cox tolerance calibration (D-09)", "",
             "Generated by `reference/fixtures/calibrate.py` from the fixtures of pprof_py "
             f"{manifest['reference']['pprof_py']['version']} and R {manifest['reference']['r']['version']} "
             f"with survival {manifest['reference']['r']['survival']}. Ratios are observed difference over allowed "
             "difference under testkit's `Tolerance` rule. Agreement between the two validated implementations "
             f"must be at most 1; every negative control must be at least {MARGIN:g}.", "",
             "| Case | Ties | Quantity | Class | pprof_py vs R | Weakest negative control | OK |",
             "|---|---|---|---|---|---|---|"]
    for case, ties, label, cls, agreement, weakest, ok in rows:
        agreement_text = f"{agreement:d}" if isinstance(agreement, int) else f"{agreement:.3g}"
        weakest_text = "—" if weakest is None else f"{weakest:.3g}"
        lines.append(f"| {case} | {ties} | {label} | {cls} | {agreement_text} | {weakest_text} | {'yes' if ok else '**no**'} |")
    lines += ["", f"Result: {'all checks pass' if not failures else f'{len(failures)} checks fail'}."]
    os.makedirs(os.path.join(ROOT, "docs", "parity"), exist_ok=True)
    with open(os.path.join(ROOT, "docs", "parity", "cox-calibration.md"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print("\n".join(lines[-1:]))
    for failure in failures:
        print("FAIL", *failure)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
